services:
  mc:
    image: itzg/minecraft-server:java17
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: SPIGOT
      VERSION: 1.12.2
      MEMORY: 2G
      JVM_OPTS: "-javaagent:slimeworldmanager-classmodifier-2.2.1.jar -Dfile.encoding=UTF-8"
      OPS: |
        199t8
    volumes:
      - ./Bedwars/Bedwars:/data
      - ./plugins:/plugins
