#!/bin/bash

# .: https://polymart.org/resource/free-bedwars-setup-like-hypixe.4292
# ./plugins: https://ci.citizensnpcs.co/job/Citizens2/3478/
#            https://www.spigotmc.org/resources/tab-1-5-1-21-1.57806/

docker-compose down -v
rm -rf Bedwars
python3 -m zipfile -e Bedwars.zip Bedwars
cp -rT 'Bedwars/Update 1.3.1.3' Bedwars/Bedwars
