services:
  mc:
    image: itzg/minecraft-server:java8
    ports:
      - 25565:25565
    environment:
      EULA: "true"
      VERSION: 1.8.1
      WORLD: https://static.planetminecraft.com/files/resource_media/schematic/missile-wars-mini-game-map-1-8-1.zip
      ENABLE_COMMAND_BLOCK: "true"
      OPS: |
        199t8
