services:
  mc:
    image: itzg/minecraft-server:java17
    ports:
      - 25565:25565
    environment:
      EULA: "true"
      VERSION: 1.20.1
      WORLD: https://static.planetminecraft.com/files/resource_media/schematic/rocket-riders-e181.zip
      OPS: |
        199t8
